class AppLocalization {
  final String languageCode;

  AppLocalization(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Vaultify',
      'nav_vault': 'Vault',
      'nav_keys': 'Keys',
      'nav_stats': 'Stats',
      'nav_setup': 'Setup',
      'search_hint': 'Search Account...',
      'no_accounts': 'No Accounts Saved Yet',
      'add_account': 'Add Account',
      'edit_category': 'Edit Category',
      'change_category': 'Change Category',
      'details': 'Account Details',
      'username_email': 'Username / Email',
      'password': 'Password',
      'notes': 'Notes',
      'close': 'Close',
      'copied': 'Copied to clipboard',
      'delete_title': 'Delete Account?',
      'delete_confirm': 'Are you sure you want to delete',
      'cancel': 'Cancel',
      'no_way': 'No Way',
      'delete': 'Delete',
      'add_new_account': 'Add New Account',
      'service_name': 'Service Name',
      'service_hint': 'e.g. Google, Netflix, Spotify',
      'category': 'Category',
      'save_account': 'Save Account',
      'save_success': 'Account Saved Successfully!',
      'fill_service': 'Please fill service name',
      'fill_username': 'Please fill username',
      'fill_password': 'Please fill password',
      'gen_title': 'Password Generator',
      'gen_strength_weak': 'Weak (Easy to crack)',
      'gen_strength_fair': 'Fair (Could be stronger)',
      'gen_strength_strong': 'Strong (Secure)',
      'gen_strength_god': 'God (Impossible to crack!)',
      'gen_length': 'Password Length',
      'gen_uppercase': 'Uppercase (ABC)',
      'gen_lowercase': 'Lowercase (abc)',
      'gen_numbers': 'Numbers (123)',
      'gen_symbols': 'Symbols (!@#)',
      'gen_refresh': 'Refresh Password',
      'gen_copy_success': 'Password Copied!',
      'stats_title': 'Vault Insights',
      'stats_total': 'Total Accounts Saved',
      'stats_distribution': 'Category Distribution',
      'stats_no_data': 'No data to analyze yet King!',
      'settings_title': 'Settings',
      'settings_security': 'Security',
      'settings_biometric': 'Biometric Lock',
      'settings_appearance': 'Appearance',
      'settings_dark_mode': 'Dark Mode',
      'settings_language': 'Language',
      'settings_about': 'About Vaultify',
      'settings_footer_crafted': 'Crafted with Passion',
      'change_lang_title': 'Select Language',
      'cat_social': 'Social Media',
      'cat_entertainment': 'Entertainment',
      'cat_work': 'Work/Email',
      'cat_finance': 'Finance',
      'cat_games': 'Games',
      'cat_shopping': 'Shopping',
      'cat_other': 'Other',
    },
    'id': {
      'app_name': 'Vaultify',
      'nav_vault': 'Brankas',
      'nav_keys': 'Kunci',
      'nav_stats': 'Statistik',
      'nav_setup': 'Setelan',
      'search_hint': 'Cari Akun...',
      'no_accounts': 'Belum Ada Akun Tersimpan',
      'add_account': 'Tambah Akun',
      'edit_category': 'Ubah Kategori',
      'change_category': 'Pilih Kategori Baru',
      'details': 'Detail Akun',
      'username_email': 'Username / Email',
      'password': 'Password',
      'notes': 'Catatan',
      'close': 'Tutup',
      'copied': 'Berhasil disalin',
      'delete_title': 'Hapus Akun?',
      'delete_confirm': 'Apakah kamu yakin ingin menghapus',
      'cancel': 'Batal',
      'no_way': 'Tidak Jadi',
      'delete': 'Hapus',
      'add_new_account': 'Tambah Akun Baru',
      'service_name': 'Nama Layanan',
      'service_hint': 'misal Google, Netflix, Spotify',
      'category': 'Kategori',
      'save_account': 'Simpan Akun',
      'save_success': 'Akun Berhasil Disimpan!',
      'fill_service': 'Isi Nama Layanan Dulu Bro',
      'fill_username': 'Isi Username Dulu Bro',
      'fill_password': 'Isi Password Dulu Bro',
      'gen_title': 'Pembuat Password',
      'gen_strength_weak': 'Lemah (Gampang Dibobol)',
      'gen_strength_fair': 'Lumayan (Bisa Lebih Kuat)',
      'gen_strength_strong': 'Kuat (Aman Jaya)',
      'gen_strength_god': 'Dewa (Gak Ada Obat!)',
      'gen_length': 'Panjang Karakter',
      'gen_uppercase': 'Huruf Besar (ABC)',
      'gen_lowercase': 'Huruf Kecil (abc)',
      'gen_numbers': 'Angka (123)',
      'gen_symbols': 'Simbol (!@#)',
      'gen_refresh': 'Segarkan Password',
      'gen_copy_success': 'Password Berhasil Dikopi!',
      'stats_title': 'Insight Brankas',
      'stats_total': 'Total Akun Tersimpan',
      'stats_distribution': 'Distribusi Kategori',
      'stats_no_data': 'Belum ada data untuk dianalisis King!',
      'settings_title': 'Pengaturan',
      'settings_security': 'Keamanan',
      'settings_biometric': 'Kunci Biometrik',
      'settings_appearance': 'Tampilan',
      'settings_dark_mode': 'Mode Gelap',
      'settings_language': 'Bahasa',
      'settings_about': 'Tentang Vaultify',
      'settings_footer_crafted': 'Dibuat dengan Sepenuh Hati',
      'change_lang_title': 'Pilih Bahasa',
      'cat_social': 'Media Sosial',
      'cat_entertainment': 'Hiburan',
      'cat_work': 'Kerja / Email',
      'cat_finance': 'Keuangan',
      'cat_games': 'Game',
      'cat_shopping': 'Belanja',
      'cat_other': 'Lainnya',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  String getLocalizedCategory(String cat) {
    switch (cat) {
      case 'Social Media': return translate('cat_social');
      case 'Entertainment': return translate('cat_entertainment');
      case 'Work/Email': return translate('cat_work');
      case 'Finance': return translate('cat_finance');
      case 'Games': return translate('cat_games');
      case 'Shopping': return translate('cat_shopping');
      case 'Other': return translate('cat_other');
      default: return cat;
    }
  }
}
